export const ActionTypes = {
    FETCH_FOOD_LIST_REQUEST: "FETCH_FOOD_LIST_REQUEST",
    FETCH_FOOD_LIST_SUCCESS: "FETCH_FOOD_LIST_SUCCESS",
    FETCH_FOOD_LIST_FAIL: "FETCH_FOOD_LIST_FAIL",
    FETCH_REVIEWERS_STATISTICS_REQUEST: "FETCH_REVIEWERS_STATISTICS_REQUEST",
    FETCH_REVIEWERS_STATISTICS_SUCCESS: "FETCH_REVIEWERS_STATISTICS_SUCCESS",
    FETCH_REVIEWERS_STATISTICS_FAIL: "FETCH_REVIEWERS_STATISTICS_FAIL",
    FETCH_FOOD_STATISTICS_REQUEST: "FETCH_FOOD_STATISTICS_REQUEST",
    FETCH_FOOD_STATISTICS_SUCCESS: "FETCH_FOOD_STATISTICS_SUCCESS",
    FETCH_FOOD_STATISTICS_FAIL: "FETCH_FOOD_STATISTICS_FAIL",
};